"""initial schema

Revision ID: a66420a825e1
Revises: 
Create Date: 2026-07-10 14:59:16.545580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66420a825e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produce_catalog',
    sa.Column('produce_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_te', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'dozen', 'bundle', name='unit_type'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('produce_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('farmer', 'customer', 'admin', name='user_role'), nullable=False),
    sa.Column('location_pincode', sa.String(length=10), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('listings',
    sa.Column('listing_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('produce_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('vision_grade', sa.Enum('A', 'B', 'C', 'REJECTED', name='vision_grade'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'negotiating', 'accepted', 'rejected', 'sold', name='listing_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['produce_id'], ['produce_catalog.produce_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('price_table',
    sa.Column('price_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('produce_id', sa.UUID(), nullable=False),
    sa.Column('region_pincode_prefix', sa.String(length=3), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_margin_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['produce_id'], ['produce_catalog.produce_id'], ),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('produce_id', 'region_pincode_prefix', 'valid_date', name='uix_produce_region_date')
    )
    op.create_table('negotiation_sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.SmallInteger(), nullable=False),
    sa.Column('farmer_ask', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('engine_decision', sa.Enum('ACCEPT', 'COUNTER', 'REJECT', name='engine_decision'), nullable=False),
    sa.Column('counter_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('farmer_response', sa.Enum('ACCEPT', 'REJECT', name='farmer_response'), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', name='order_status'), server_default=sa.text("'confirmed'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('agreed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='transaction_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('orders')
    op.drop_table('negotiation_sessions')
    op.drop_table('price_table')
    op.drop_table('listings')
    op.drop_table('users')
    op.drop_table('produce_catalog')
    # ### end Alembic commands ###
